package com.example.stoppointui;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemSelectedListener;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.TextView;

public class Routes extends Activity implements OnItemSelectedListener{
	TextView sd,dd;
	
	private static final String[] paths = { "Khed Shivapur",
			"Shri Krushna Nagar", "15 August Lodge",
			"15 Number / Manjri Phata", "15 Number",
			"15 Number/ Kaspate Wasti", "40 Aundh Road", "509 Area",
			"512 Factory", "5th Mile", "A.D. Camp Chowk", "A.D. Camp", "Aamba",
			"Abhi Chemical", "Abhinav Kala Vidyalaya", "Adarsh Nagar",
			"Adinath Soc", "Aditya Group", "Adler Engg. Company",
			"Agalambe Phata", "Agalambe Gaon", "Agarwal Colony",
			"Agha Khan Palace", "Aher Garden", "Ahilya Society",
			"Ahilyadevi School", "Ahire Gaon", "Ahire Phata", "Ahire Gate",
			"Ahireshwar Wadi", "AIT", "Ajantha Nagar Corner", "Ajantha Nagar",
			"Ajantha Nagar Society", "Ajay Nivas", "Akashwani",
			"Akshay Sanshri", "Akurdi Khandoba maal", "Akurdi Railway Station",
			"Akurdi", "Alandi Gaon Phata", "Alandi Jakatnaka", "Alandi Phata",
			"Alandi", "Alankar Chowk", "Alankar Police Chowki",
			"Alankar Talkies", "Alegaonkar High School", "Alegaonkar School",
			"Aler Wear Housing", "Alfa Laval", "Alfa Laval Company",
			"Alka Talkies", "Alpha Paper Mill", "Amarjai Mandir",
			"Ambedkar Bhavan", "Ambedkar Colony",
			"Ambedkar Putala / Pune Station", "Ambedkar Putala",
			"Ambedkar Sanskritik Bhavan", "Ambedkar Society", "Ambedkarnagar",
			"Ambegaon Phata", "Ambegaon", "Ambil Odha Colony",
			"Ammunition Factory", "Amralewadi",
			"Ammunition Factory Co-Op Society", "Ammunition Factory Gate",
			"Anand Ashram", "Anand Dhyan Kendra", "Anand Park",
			"Anand Vidyaniketan", "Anandnagar",
			"Anant Nagar / Devendra Mangal Karyalaya", "Anant Talkies",
			"Andhashala", "Ankur Bungalow", "Ankush Chowk",
			"Annabhau Sathenagar", "Aple Ghar", "Apollo Talkies",
			"Appa Balwant Chowk Bhudhawar Chowk", "Appa Balwant Chowk",
			"Appa Balwant Chowk / Dn. City post",
			"Appa Balwant Chowk / Vasant talkies", "Appughar",
			"Appughar Corner", "Apsara Talkies", "Aranyeshwar Corner",
			"Aranyeshwar Mandir", "Archana Restaurant", "ARDE Colony",
			"ARDE Gate", "ARDE Office", "ARDL Colony", "ARDL Office",
			"Army College", "Arsenal Factory Gate", "Artificial Limb Centre",
			"Arts Faculty", "Arvi Phata", "Aryabhushan Press", "Aryoga Kendra",
			"Ashirwad Bungalow", "Ashish Garden", "Ashok Leyland Co./ Shubham",
			"Ashok Leyland Godown", "Ashok Stambha", "Ashok Theatre",
			"Ashoka Society", "Ashoka", "Ashok Nagar", "Asvi Training Company",
			"Athawale Chowk", "Atlas", "Atmavishwas Building", "Auditorium",
			"Aundh Gaon", "Aundh Post", "Aundh Shala", "Aundh", "Avid Path",
			"Avinash Mangal Karyalaya", "Avtade Wadi Phata", "Awasar Wadi",
			"Azad Nagar", "B.U.Bhandari", "Baburao Smarak", "Badade Vasti",
			"Bafna Industries", "Bagal Wasti", "Bahirat Wadi", "Bahul Gaon",
			"Bahul Phata", "Bajaj Auto", "Bajaj Showroom", "Bajar Mala",
			"Bakawolf Colony", "Bakery", "Bakuri Phata", "Bal Shikshan Mandal",
			"Balaji Kata Corner", "Balaji Palace", "Balaji Super Market",
			"Balaji Nagar", "Balbharati / Symbiosis", "Balewadi Phata",
			"Bale Wadi", "Balgandharva", "Balkawade Wasti", "Balsadan",
			"Bandal Farm", "Baner", "Baner Gaon", "Baner Odha", "Baner Phata",
			"Bangar Wasti", "Bank Of India", "Bank Of Maharashtra",
			"Bankar Wasti", "Bapugi Buva Khind",
			"Bavdhan Khind/ Chandani Chowk", "Bavdhan Phata", "Bavdhan Gaon",
			"Bazaar Samittee", "Belekar Wasti", "Benkar Wasti",
			"Bhadale Wasti", "Bhagwat Vihar", "Bhagwat Wasti", "Bhahirat Wadi",
			"Bhairaoba Mandir Nasrapur", "Bhairav Nagar",
			"Bhairav Nath Mandir", "Bhairoba Nagar",
			"Bhairoba Nala Police Station", "Bhairoba Nala",
			"Bhairoba Nala Police Chowki", "Bhairoba Nala Pumping Station",
			"Bhaji Mandai", "Bhakti Shakti", "Bhakti Shakti Depot", "Bham",
			"Bhandari Company / Wadekar Wasti", "Bhandari Company",
			"Bhandari Hospital", "Bhandari Niwas", "Bhandarkar Institute",
			"Bhande Wadi", "Bhapkar Petrol Pump", "Bhapkar",
			"Bharat English School", "Bharati Vidyapeth Gate",
			"Bharati Vidyapeth Hostel", "Bharati Vidyapeth", "Bharati Nagar",
			"Bharatjyoti Society", "Bhare Phata", "Bhar Gaon Industries",
			"Bhat Nagar", "Bhaurao Patil Chowk", "Bhavani Mata Mandir",
			"Bhave Hospital", "Bhegde Wadi Phata", "Bhekrai Nagar",
			"Bhikardas Maruti", "Bhilare Wadi", "Bhilare Wadi Chowk",
			"Bhimjyoti Society", "Bhim Nagar", "Bhoi Phata", "Bhoir Nagar",
			"Bhondwe House", "Bhondwe Wasti", "Bhosale Wasti", "Bhosari",
			"Bhosari Police Station", "Bhose Phata", "Bhu Gaon",
			"Bhukum Ashram", "Bhukum", "Bhumkar Wasti", "Bhusari Colony",
			"Bhushan Society", "Bibwewadi", "Big India", "Bijli Nagar Pool",
			"Bijli Nagar", "Bildip Society", "Binawat Township",
			"Birla Hospital", "Blue Diamond Hotel", "Bodygate",
			"Bombay Garage", "Bombay-Poona Road", "Bopodi",
			"Bopodi Jakat Naka", "Borate Wasti", "Borkar Wasti", "Bormal",
			"Botanical Garden", "Boys Battalion", "Bramhan Wadi",
			"Bremen Chowk", "Buddha Vihar", "Budhrani Hospital", "Bund Garden",
			"Bungalow No. 158", "Bungalow No. 105", "Bupusaheb Magar Wasti",
			"Burkegaon Shala", "Burmshell", "Bypass Highway", "C Ward",
			"Cable Company", "Canal Company", "Canal Zopadpatti", "Canal",
			"Cantonment Board", "Cantonment Hospital", "CDO Office",
			"Central Restaurant", "Central School", "Century Enka Company",
			"Century Enka Corner", "Century Enka", "Chacha Halwai",
			"Chakan Phata", "Chaitanya Bungalow", "Chaitanya Nagar",
			"Chaitanya Vidyalaya Mitha Nagar", "Chakan Market Yard",
			"Chakan Oil Mill", "Chakan S.T.Stand", "Chakankar Mala",
			"Chandan Nagar", "Chandni Chowk", "Chandrabhaga Nagar",
			"Chankan S.T. Stand", "Chapekar Chowk", "Charoli Gaon",
			"Charoli Phata", "Chaturshrungi Mandir", "Chaturshrungi",
			"Chaudhari Dhaba", "Chavan Mala", "Chavan Nagar", "Cheladi Phata",
			"Chetna Vidyalaya", "Chinchwad Station", "Chikhali Gaon",
			"Chikhali", "Children School", "Chillal Masala", "Chincha",
			"Chinchawad Gaon", "Chinchawade Corner", "Chinchawade Farm",
			"Chinchawade Nagar Corner", "Chincheche Zad", "Chincholi",
			"Chinchwad Gaon Corner", "Chinchwade Farm", "Chintamani Nagar",
			"Chitrashala", "Chitrashala / Gokhale Hall", "Choudhari Baug",
			"Choudhari Dhaba", "Choudhari Phata", "Choudhari Wasti",
			"Chudaman Tallim", "Chuphula", "Church", "Chutke Vasti",
			"Cipla Centre", "Cirt", "Cisv", "City Post", "Classic Hotel",
			"COD Corner", "COD Depot", "Collector Office", "Colony Bungalow",
			"Commonwealth", "Computer College", "Co-Op Engineering",
			"Corporation Office", "Corporation school",
			"Council Hall Police Chowki", "Culvart", "Cummins Chowk",
			"Cyprus Gate 1", "Cyprus Post", "D Prabhag Karyalaya", "D Ward",
			"D.Y.Patil college Corner", "D.Y.Patil college",
			"D.Y.Patil School", "D2 Circle", "Dabhade Vasti", "Dabhade Wasti",
			"Dagde Vasti", "Dagdikhan", "Dagdinagoba", "Dahanukar Colony",
			"Daichi Company", "Dairy Farm", "Dak Bangalow",
			"Dakshinmukhi Maruti", "Dalvi Vasti", "Dandekar Pool",
			"Dandekar Pul", "Dangat Vasti", "Dange Chowk", "Dapodi Navin Pul",
			"Dapodi", "Dapodigao", "Darekar Vasti", "Darshan Hall",
			"Dasbhuja Ganapati", "Date Engineering", "Date Stop",
			"Datta Mandir", "Datta Nagar / Gaikwad Wasti",
			"Datta Nagar Hospital", "Datta Nagar", "Dattaprasad Society",
			"Datta Wadi Corner / Padale Palace", "Datta Wadi Corner",
			"Datta Wadi Phata", "Datta Wadi Police Chowki", "Datta Wadi Pul",
			"Daulat Garden", "Daulat Nagar", "Daychi", "Deccam Gymkhana",
			"Deccan College", "Deccan Corner", "Deccan Gymkhana",
			"Deccan Poltry", "Deep Bungalow", "Defence Colony",
			"Defence Talkies", "Dehu Gaon Phata", "Dehu Grampanchyat",
			"Dehu Phata", "Dehu Road Bazaar", "Dehu Bazaar", "Dehu Gaon",
			"Dehu Gaon Grampanchayat", "Dehu Road Police Line",
			"Dehu Road Police Station", "Dehu Road Station", "Deluxe Chowk",
			"Deluxe Talkies", "Deluxe", "Desai Poultry Farm", "Deshmukh Wasti",
			"Deshmukh Wadi", "Devgiri Bungalow", "Devi Link",
			"Devpuri Maharaj Mandir", "Dhaireshwar Mandir", "Dhaireshwar",
			"Dhairi Gaon", "Dhairi Gaon / Maruti Mandir", "Dhairi Phata",
			"Dhamale Wasti", "Dhananjay Society", "Dhanaraj Mangal Karyalaya",
			"Dhangarbaba", "Dhankawadi Post", "Dhankawadi", "Dhanori Gaon",
			"Dhanori Gaon Shala", "Dharan", "Dharma Nagar",
			"Dharmveer Shala / Garware College", "Dharmveer Shala",
			"Dhawade Wasti", "Dhere Bungalow", "Dholepatil Farm",
			"Dhore Wasti", "Dhumaltali", "Dhume Wadi", "Diamond Watch Company",
			"Dighi Corner", "Dighi Corner(Odha)", "Dighi", "Dive Phata",
			"Dnyaneshwar Old House", "Dongar Gaon Phata", "Donger Veet Bhatti",
			"Donger Matha", "Donje Gaon", "Donje Phata", "Doorsanchar",
			"D.P. Road", "Dr. Bhaba Davakhana", "Dr. Sayyad Davakhana",
			"DSK Gate", "DSK Showroom", "DSK Vishwa", "Dudhane Wasti",
			"Durance Bungalow", "Duravankur Bungalow", "Durgani Electronics",
			"Dynanesh Society", "Dynaneshwar Old House", "Dynaneshwar Bhinta",
			"Dynaneshwar Paduka Chowk", "Dynaneshwar Society",
			"E.S.I. Hospital", "E.S.I. Office", "Eagle Company", "Eagle Flask",
			"Eklavya College", "Ekora Company", "Electronic House",
			"Empatronics Company", "Empire Estate", "Employment Office",
			"Enclave Building", "Engineering College Hostel",
			"Engineering College", "Engle Hospital", "Eshanya Nagari",
			"Excelsior Talkies", "Exide Battery", "Factory Hospital",
			"Factory Road", "Family Camp", "Farshi Karkhana", "Fatima Nagar",
			"Fergusson College", "Film Institute", "Fire Brigade",
			"Fiskar Company", "Forest Office Road", "Forest Office",
			"Fuel Depot", "Gadikhana / Mandai", "Gadikhana /Bhikardas",
			"Gadikhana", "Gadital", "Gaimukh", "Gajanan Mandir",
			"Gananjay Society", "Ganapati Mandir / Munjaba Wasti",
			"Ganapati Mandir", "Ganapati Society", "Gandhi Acid Company",
			"Gandhi Bhavan / Vadacha Stop", "Gandhi Bhavan Phata",
			"Gandhi Bhavan Shala", "Gandhi Training College", "Ganesh Hotel",
			"Ganesh Mala", "Ganesh Mandir", "Ganesh Nagar Corner",
			"Ganesh Nagar", "Ganesh Park", "Ganesh Peth", "Ganesh Vision",
			"Ganga Village/ Ganesh Mangal Karyalaya", "Gangadham",
			"Ganga Nagar / Pradhikaran", "Ganga Nagar", "Gangaram Park",
			"Ganj Peth Police Chowk", "Ganjve Chowk / Deccan Corner",
			"Ganjve Wadi", "Ganpati Chowk", "Ganpati Mandir",
			"Ganpati Matha Mandir / Malwadi", "Ganpati Matha / Malwadi",
			"Garden City", "Garmal", "Garrison Engineer", "Garware Bungalow",
			"Garware College", "Garware Company", "Gate No. 1",
			"Gavade Colony", "Gavade Farm", "Gavhane Wasti", "Gavade Wasti",
			"Gavhane Nagar", "Gavli Math", "Gavli Wada", "Gayakwad Wasti",
			"Geeta Mangal Karyalya", "Gents Hostel", "GF Filters",
			"Ghat Utaar Walan", "Ghat", "Ghata Khali / Poker Wasti",
			"Ghenanand Wasti", "Ghode Gao Phata", "Ghodyachi Paga",
			"Gholap College", "Gholap Vidyalaya", "Ghore Budruk",
			"Ghore Khurda", "Ghore Shala", "Ghorpade Post", "Ghorpade School",
			"Ghorpadi Peth Colony", "Ghorpadi Peth Police Chowk",
			"Ghorpadi Peth / Municipal Colony", "Ghorpadi Post",
			"Ghorpadi Shala", "Ghotawade Gaon", "Ghotawade Phata",
			"Ghule Wasti", "Giridhar Bhavan", "Giri Nagar", "Giriraj",
			"Girls Host el", "Gite Wasti", "Goal Market", "Godown",
			"Gogal Wadi", "Gokhale Hall", "Gokhale Mala", "Gokhale Nagar",
			"Gokhale Nagar Police Line", "Gokhale Nagar Police Vasahat",
			"Gokhale Nagar Shala", "Gokul Bhavan", "Gokul Hospital",
			"Gokul Hotel", "Gokul", "Gokul Nagar", "Gole Market", "Gole Wadi",
			"Golibar Maidan", "Golmarket", "Gondhale Nagar",
			"Good Luck Chowk / Deccan Gymkhana", "Gopalpatti", "Gopi Chaal",
			"Gopi Chawl", "Gore Khurd", "Gosavi Wasti", "Govind Halwai Chowk",
			"Govt. Polytechnic", "GPO", "Grampanchayat Office", "Grand Hotel",
			"Green Acres", "Green Oaks Company", "Guardroom Gate",
			"Gujarat Colony", "Gujar Nagar / Laxman Nagar", "Gujar Nagar",
			"Gujar Wadi Phata", "Gujrati Dharmashala", "Gujrati Shala",
			"Gul Ali", "Gulab Nagar", "Gulmohor Society", "Gulnur Farm",
			"Gultekadi Zopadpatti", "Gunjan Talkies", "Gupta Steel",
			"Gurdev Nagar", "Guru Ganesh Nagar", "Guru Shankar Math",
			"Gurudwara Canto. Hospital", "Gurudwara", "Gurujan Society",
			"Guruprasad Bungalow", "H Type Quarters", "H.A. Factory",
			"H.A.Company", "H.A.Corner", "H.D.F.C", "Hadapsar Bazar",
			"Hadapsar Gadital", "Hadapsar Gaon", "Hagahawanepadal",
			"Hagwane Wasti", "Hande Wadi Gaon", "Hanuman Chowk",
			"Happy Thoughts", "Harihareshwar Mandir", "Harijan Wasti",
			"Harimaan Wasti", "Hariprasad Bungalow", "Harpale Wasti",
			"Harpude Wasti", "Harshwardhan Hotel", "Highway Corner", "Hingne",
			"Hingne Corner", "Hingne Khurda", "Hingne Rasta",
			"Hingne Township", "Hinjawadi", "Hinjawadi Police Station",
			"Hinjewadi Gaon", "Hinjewadi Infosys Company Phase 1",
			"Hinjewadi Infosys Company", "Hinjewadi Jakat Naka",
			"Hinjewadi Phata", "Hinjewadi Police Station", "Hirabaug",
			"HMRL Company", "Hockey Ground", "Hole Wasti",
			"Holkar Pool corner", "Holkar Pul", "Holkar Wadi",
			"Holkar Water Supply", "Holkar Waterworks", "Homegaurd",
			"Hood Company", "Hospital", "Housing Board Corner",
			"HP Petrol Pump", "HRA Company", "Hypic Company", "I.T.I Chowk",
			"I.T.Park / Hinjawadi", "IAT Canteen", "IAT College",
			"ICL Company", "Ideal Colony", "ILC Company", "IMD Colony",
			"Inamdar Wasti", "Income Tax Office", "Indian Card Clothing",
			"Indian Card Company", "Indian Card", "Indian Hume Pipe Company",
			"Indira Nagar", "Indraprabha / Mamurdi", "Indraprabha",
			"Indrayani Darshan", "Indrayani Dhaba", "Indrayani Nagar",
			"Indrayani Pul", "Industrial Company", "Infosys Company Phase 2",
			"Ingale Padal", "Ingale Colony", "Ingale Hospital", "IT Tower",
			"ITI", "J Type", "J.K. Industries", "J.P. Industries",
			"Jabhulkar Nagar", "Jadhav Bungalow", "Jadhav Wasti",
			"Jadhav Wadi", "Jadhav Nagar", "Jadhav Wadi phata", "Jagtap Dairy",
			"Jagtap Nagar", "Jai Bhavani Nagar", "Jai Bhavani Warehousing",
			"Jaidev Nagar", "Jaihind School", "Jaihind Vidyalaya",
			"Jaikar Bungalow", "Jain Boarding", "Jain College", "Jain Mandir",
			"Jaishree Talkies", "Jakate Wasti", "Jakat Naka", "Jalindrebaug",
			"Jamadar Wasti", "Jambe", "Jambhlekar Wasti", "Jambhulkar Chowk",
			"Jambhulkar Nagar", "Jambhul Wadi", "Jamtani Chowk",
			"Janakbaba Darga", "Jangali Maharaj", "Jangali Maharaj Mandir",
			"Janwadi Corner", "Janwadi", "Jatap Nagar", "Jawalkar Hospital",
			"Jayanand Khira", "Jayashri Talkies", "Jayesh Mangal Karylaya",
			"Jeevan Hospital", "Jijamata Baug", "Jijamata Chowk",
			"Jivan Shikshan Mandir", "Jog Engineering", "Joseph Society",
			"Juna Jakat Naka", "Juna Motor Stand", "Juna Pulgate",
			"Juna S.T. Stand", "June Bolhai Mandir", "Jyogi School",
			"Jyoti Ashram", "Jyoti School", "Jyotiba Nagar", "K.E.M. Hospital",
			"K.S.B. Chowk", "Kachghar", "Kachara Depot", "Kachre Wasti",
			"Kad Wasti", "Kadam Wasti", "Kadbakutti", "Kadus Phata",
			"Kaharal Wadi", "Kailas Wahan Udyog", "Kakde Wasti", "Kala Khadak",
			"Kalamkar Wasti / Saikar Wasti", "Kalamkar Wasti",
			"Kala Nagar / Balagi Nagar", "Kala Nagar", "Kalas Corner", "Kalas",
			"Kalashankar", "Kalbhor Nagar", "Kalbhor Wasti",
			"Kaleborate Nagar", "Kalector Kacheri", "Kale Wadi Phata",
			"Kale Wadi", "Kalika Mata Mandir", "Kalpataru Society",
			"Kalubai Mandir", "Kalukh Shetmala", "Kalyan Gaon",
			"Kalyani Bungalow", "Kalyani Nagar", "Kalyani Pul",
			"Kamala Nehru Hospital", "Kamaljai Nagar",
			"Kamalnayan Bajaj School", "Kamela", "Kamgar Nagar",
			"Kamshet Corner", "Kamshet", "Kanda Eng. Company",
			"Kanda-Lasun Sanshodhan Kendra", "Kandage Park",
			"Kandhare Poultry Farm", "Kandlasoon Kendra", "Kane Phata",
			"Kanifnath Society", "Kanyashala", "Karachi Chowk", "Karade Wasti",
			"Karan Greens", "Karandi Gaon", "Karandi Kaman", "Karandi Phata",
			"Karhar Company", "Karnataka High School", "Karve Putala",
			"Karve Nagar Bus Stand", "Karve Nagar", "Kasaba Police Chowki",
			"Kasar Amboli", "Kasar Wadi", "Kasba Peth Police Chowki",
			"Kaspate Wasti", "Kasturba Vashat", "Kasturba Gandhi Shala",
			"Kasturba Gen Hospital", "Kasturba Zopadpatti", "Kasture Chowk",
			"Kasturi Market", "Kate Wasti", "Kate Puram", "Katke Wasti",
			"Katraj Bhandar", "Katraj By Pass Chowk", "Katraj Dairy",
			"Katraj Dudh Dairy", "Katraj Dudh Dairy / Sarpodyan",
			"Katraj Milk Dairy", "Katraj", "Kava Path Rasta", "Kavade Nagar",
			"Kavade Wasti", "Kavadi Path Rasta", "Kavadi Path", "Kawade Nagar",
			"Kedari Nagar Corner", "Kedari Nagar", "Kendriya Jalkendra",
			"Kendriya Vidyalaya", "Keshav Nagar", "Kesnand Phata",
			"Kesri Wada", "Khadakwadi Phata", "Khadakwasala Gaon",
			"Khadakwasala Dharan", "Khadi Machine", "Khadki Bazaar",
			"Khadki Police Station", "Khadki Post",
			"Khadki Railway Station Corner", "Khadki Railway Station",
			"Khan Road", "Khanapur", "Khandoba Mal", "Khandoba Mandir Corner",
			"Khandoba Mandir / Sai Nagar", "Khandwe Bungalow", "Khandwe Nagar",
			"Kharadi Gaon", "Kharal Wadi", "Kharki Bazaar", "Kharki Post",
			"Kharki Station", "Khesepark", "Khirid Wasti", "Khondwa Khurda",
			"Khondwa Shala", "Kirkat Wadi", "Kirloskar Company",
			"Kirloskar Oil Engine", "Kirtane Baug", "Kirti Grapes",
			"Kiwale Phata", "Kiwale", "Kodre Wasti", "Kohima Line",
			"Kolhe Wadi Post", "Konark Nagar Corner", "Kondave Dhavade",
			"Kondhanpur", "Kondhanpur Boudh Wasti", "Kondhanpur Phata",
			"Kondhawa Hospital / Yewale Wadi", "Kondhawa Bu.",
			"Kondhawa Bu. Corner", "Kondhawa Corner", "Kondhawa Dhavde",
			"Kondhawa Gaon", "Kondhawa Gate", "Kondhawa Hospital",
			"Kondhawa Hospital [ Yewale Wadi Phata]", "Kondhawa Khurd",
			"Kondhawa Kopare", "Kondhawa Shala", "Koregaon Bhima",
			"Kothari Colony", "Kothrud Bus Stand", "Kothrud Depot",
			"Kothrud Gaon", "Kothrud Old Stand", "Kothrud", "Koyali Phata",
			"Kranti Society", "Kranti Stambha",
			"Krishi Mahavidyalaya / Kuran Farm", "Krishi Tyfast",
			"Krushna Mandir Corner", "Krushna Mandir", "Krushna Nagar Corner",
			"Krushna Nagar", "Krushna Plaza", "Krushnai Mangal Karyalaya",
			"Krushna Nivas", "Krushna Bazar", "Kudale Baug",
			"Kudal Wadi Corner", "Kudal Wadi", "Kudge Gaon", "Kudge Stand",
			"Kukkut Palan Kendra", "Kulkarni Petrol Pump", "Kumar Park",
			"Kumar Products", "Kumbhar Wasti", "Kumbhar Wada", "Kumbre Park",
			"Kungir Wadi Gaon", "Kunjir Mala", "Kunjir Vihir",
			"Kunjir Wada Phata", "Kunjir Wadi Phata", "Kunte Chowk",
			"Kuruli Gaon", "Kusalkar Putala", "Kutale Wasti", "Kutira Complex",
			"L.I.C. Corner", "L.I.C. Colony", "Labour Office",
			"Ladbachi Wasti", "Lademark Garden", "Ladies Hostel",
			"Lagad Wasti", "Lakaki Bungalow", "Lakshmi Mandir", "Lakud Bazaar",
			"Lakud Wasti", "Lal Mandir", "Laman Wasti", "Lande Wadi",
			"Lavale Phata", "Lavale Gaon", "Law College", "Laxman Nagar",
			"Laxmi Bakery", "Laxmi Colony", "Laxmi Electricals",
			"Laxmi Narayan Theatre", "Laxmi Pro Stores", "Laxmi Residency",
			"Laxmi Nagar Corner", "Laxmi Nagar Police Chowki",
			"Laxmi Narayan Talkies", "Laxmi Narayan", "Lipane Wasti",
			"Lison Company", "Lohagaon", "Lokhandi Darvaja",
			"Lokmanya Hospital", "Lokmanya Nagar / Petrol Pump",
			"Lokmanya Nagar", "Lokmanya", "Lole Wasti",
			"Lonar Odha /Sai Satyam", "Lonar Odha", "Loni Phata",
			"Loni Station", "Lonikand Phata", "Lonikand",
			"Lonkar Wasti / Angaraj Dhaba", "Lonkar Wasti",
			"Lower Indira Nagar", "Loyola High School", "Lucky Farm",
			"Lulla Nagar", "M 23", "M 30", "M.E.S. Waterworks",
			"M.I.D.C Canteen", "M.K.Hotel", "Madhurmilan Karyalaya",
			"Madiwale Colony", "Madusanchay Society", "Mafatlal Bungalow",
			"Mafco Company", "Magar College", "Magar Vidyamandir",
			"Magarpatta Clinic", "Magarpatta Davakhana", "Magarpatta Hospital",
			"Magarpatta Shala", "Magazine", "Mahadev Mandir Paduka",
			"Mahadev Mandir", "Mahadev Nagar", "Mahadji Shinde Chowk",
			"Mahalaxmi Electricals", "Mahamad Wadi Goan",
			"Mahamad Wadi Jakat Naka", "Maharashtra Bank",
			"Maharashtra Housing Board", "Maharashtra Mandal",
			"Maharshi Nagar Shala", "Maharshi Nagar",
			"Mahatma Gandhi Bus Stand", "Mahatma Gandhi Stand",
			"Mahatma Phule Chowk", "Mahavir Company", "Mahesh Nagar",
			"Mahesh Nagar Corner", "Mahindra Company", "Mahmadwadi Shala",
			"Main Building", "Malawale Nagar", "Maldhakka", "Malkhed",
			"Mal Nagar", "Mal Wadi Phata", "Mal Wadi",
			"Mal Wadi / Ganpati Matha", "Malyacha Mala", "Mammadevi Chowk",
			"Mamurdi Phata", "Mamurdi", "Manaji Nagar", "Mandai / Gadikhana",
			"Mandai Police Chowki", "Mandai", "Mandhre Wasti", "Mandke Wasti",
			"Mandvi Khurda", "Mangal Ben Co.", "Mangal Bone Mill",
			"Mangal Karyalaya", "Mangala Bone mil", "Mangala Talkies/ Pmc",
			"Mangde Wadi Phata", "Mangde Wadi", "Manik Baug", "Manik Colony",
			"Manik Press Road", "Manik Press", "Manjri Budruk", "Manjri Farm",
			"Manjri Khurda", "Mantar Wadi", "Manta Wadi", "Mantra Shala",
			"Mariaai Gate", "Mariaai Mandir", "Markal", "Market Yard Stand",
			"Market Yard", "Market", "Marne Wadi", "Marshall Company",
			"Maruti Mandir", "Masulkar Colony", "Matal Wadi",
			"Matchwell Company", "Mate Path", "Mati Ganpati", "Medi Point",
			"Medical Store", "Meera Society", "Mega City", "Mehendale Garage",
			"Mehta Hospital", "Mental Corner", "Merada Company",
			"Mercedes Benz Corner", "M.E.S Pumping Station", "Mess",
			"Methodist Church", "M.H. Hospital", "Mhada Colony",
			"Mhada Colony / Viman Nagar", "Mhalunge Corner", "Mhalunge Goan",
			"Mhalunge", "Mhalunge Phata", "Mhaske Wasti", "Mhasoba Chowk",
			"Mhasoba Gate", "Mhatobachi Alandi", "Mhatoba Nagar Corner",
			"Mhatre Pul", "Mhatre Wasti", "M.I.D.C.", "Mile No. 10",
			"Mile No. 18", "Mile No. 19", "Mile No. 21", "Mile No. 22",
			"Mile No. 23", "Mile No. 7", "Mile No. 8", "Mile No. 9",
			"Military Chavani", "Military Hospital", "Military School",
			"Military Store", "Millenium Society", "Millenium Wasti",
			"Military Wasahat", "Minilake Company", "Mira Nagar",
			"Mira Society", "Mirta Mandal", "Mit College", "Mitha Nagar",
			"Mithila Nagari", "Mitica House", "Mitti Ka Ghar", "Model Colony",
			"Modern Bakery", "Modern High School", "Mofhatlal Bungalow",
			"Mohan Nagar", "Mohite Wadi", "Mohol Krida Sankul", "Moi Phata",
			"Mominpura", "Mordhari Phata", "More Baug", "More Vidhyalaya",
			"More Wasti", "Mor Wadi", "Mor Wadi Phata", "Morya Complex",
			"Moshi Gaon", "Moshi Phata / Chimbli Phata", "Moshi Phata",
			"Motor Parivahan / Shahid Smarak", "Mount Convent School",
			"Moze College", "Moze Vidhyalaya", "Moze Nagar",
			"Mrutunjay Mandir", "MSB Pumping Station", "Muk-Badhir School",
			"Mukund Shoba Baug", "Mukund Shobha Udyan", "Mukund Nagar",
			"Mula Pul", "Mula Road", "Mundhwa Gaon", "Mundhwa Shala",
			"Municipal Colony", "Municipal Davakhana", "Murkute Wasti",
			"Mutton Market", "MZ Building", "Nagar Palika", "Nagar Parishad",
			"Nagarraod Phata", "Nagpur Chal", "Nai Gaon", "Nai Gaon Phata",
			"Naik Bungalow", "Naik Hospital", "Naik Oval", "Nakhate Wasti",
			"Nal Stop", "Nana Peth", "Nandadeep", "Nandanvan Bungalow",
			"Nanded Gaon", "Nanded Phata", "Nandoshi Gaon", "Nandoshi Phata",
			"Nanekar Park", "Nare Ambegoan", "Narsesh Quarter",
			"Narvir Tanaji Wadi", "Nashik Phata", "Nasrapur Stand",
			"Natu Baug", "Navi Khadaki", "Navi Sanghavi",
			"Navin Hind High School", "Navin S.T. Stand", "Navin Saandas",
			"Navlakha Godown", "Navlakha Godown / Tolnaka",
			"Navsahyadri Chowk", "Navsahyadri Society", "Nay Gaon",
			"Nay Gaon phata", "NCL Colony", "NCL Gate", "NCL Hospital",
			"NCL Hostel", "NCL Lab", "NCL Laboratory", "NCL Market",
			"NDA Gate No. 10", "NDA Gate", "Neelayam Talkies",
			"Neel Jyoti Society", "Nehru Corner", "Nehru Stadium",
			"Nehru Nagar Corner", "Nehru Nagar", "NEI", "Nere Phata",
			"Nerolac Paint Company", "Netaji Subhashchandra School",
			"Netaji Nagar", "New Highway", "NFIL Company", "NIBM Corner",
			"Nigdi Corner", "Nigdi Jakat Naka", "Nigdi", "NIIT",
			"Nikam Hospital", "Nimbalkar Wasti", "Nirmal Township", "Nursery",
			"Nurses Quarters", "Officers Mess", "Ohol Wasti", "Old Bazaar",
			"Old Jakat Naka", "Old Pool Gate", "Old Pulgate", "Old S.T. Stand",
			"Oraskar Company", "Ordinance Factory Gate", "Ordinance Club",
			"P&T Colony", "Pacharne Wasti", "Pachwad",
			"Padamji / Ramoshi Gate", "Padamji Paper Mill", "Padmaji Mill",
			"Padmavati Corner", "Padmavati", "Paduka Mandir",
			"Pahadi Davakhana", "Paigude Wasti", "Paisa Fund",
			"Paisa Fund Kach Karkhana", "Panale Farm", "Panaychi Taki",
			"Panchami", "Panchvati", "Panchvati Gate", "Panchvati Nivas",
			"Pandav Nagar", "Pandit Auto Motive", "Panjarpol", "Panmala",
			"Parade Ground", "Paraj Company", "Paramhans Nagar",
			"Paranjape Hospital", "Paranjape Scheme", "Pared Ground",
			"Parihar Chowk", "Parmar Society", "Parvati Darshan",
			"Parvati Gaon", "Parvati Paytha / Mahila Mandal", "Parvati Paytha",
			"Pasalkar Wasti", "Pashan Gate", "Pashan Jakat Naka",
			"Pashan Lake", "Pashan Naka", "Pashan Tale", "Pashan Tank Rasta",
			"Pashan Tank Road", "Pashan Veet Bhatti", "Pathanbaba Darga",
			"Pathare Bungalow", "Pathare Wasti", "Patil Baug", "Patil Colony",
			"Patil Estate", "Patil Wasti", "Patwardhan Baug", "Paud Phata",
			"Paud Police Station", "Paud Gaon", "Pavna Pul", "Pawale Chowk",
			"Pawar Quarters", "Pawar Wasti", "Pawar Mala", "Pawar Wadi",
			"PC Poll Company", "Peacock Bay", "Perne Phata", "Perne Goan",
			"Peru Gate", "Peshwe Park", "Peth", "Petkar Project",
			"Petrol Pump", "Phadke Haud", "Phadtare Wasti", "Pharshi Odha",
			"Fatima Nagar school", "Philips Company", "Philips",
			"Phinolex Company", "Phuge Wadi", "Phule Nagar", "Phul Gaon",
			"Phursungi Gaon", "Phursungi Phata / Power House",
			"Phursungi Phata", "Phutka Burunj", "Pimpale Gurav",
			"Pimpale Saudagar", "Pimplekar Wasti", "Pimpale Nilakh",
			"Pimpale Nilakh Shala", "Pimpri Coorporation", "Pimpri Court",
			"Pimpri Nyayalaya", "Pimpri Road", "Pimpri Saandas", "Pimpri",
			"Pimpri Gaon", "Pingale Wasti", "Pirangut", "Pisoli Gaon",
			"Pite Phata / Shiroli Phata", "PMC Bhavan", "PMT Colony",
			"Pokar Wasti", "Police Chowki", "Police Fire Station",
			"Police Ground", "Police Line", "Police Station",
			"Police Workshop", "Polytechnic College", "Poona Poltry",
			"Poona Poultry Farm", "Post Office", "Postal Colony",
			"Poultry Farm", "Power House", "PP Road", "Prachi", "Pradhikaran",
			"Pradhikaran / Ganga Nagar / Bijali Nagar",
			"Prakash Chikan Centre", "Prakash Petrol Pump", "Prashant Society",
			"Pravin Masale", "Prayagdham Ashram", "Prayagdham Phata",
			"Premlok Park", "Press", "Primary School", "Priyanka Park",
			"Protacto Company", "Provision Stores", "Pumping Station",
			"Punawle Corner", "Punawle", "Pune Vidhyapeth", "Pune Station",
			"Pune Vidhyapeth Gate", "Pune Vidhyapeth Press", "Punekar Wasti",
			"Pushpa Mangal Karyalaya", "PWD Quarters", "Quality Kharkhana",
			"Quarter Gate", "Queen Mary Technical", "Qurtatras",
			"R.T.O Office", "Race Course", "Race Course Maidan",
			"Radhakrishna Nagar", "Rahatani Gaon", "Rahatani Phata",
			"Rahatani", "Rahata Wade", "Rahatne Phata", "Raikar Wasti",
			"Railway Crossing No. 2", "Railway Crossing", "Railway Gate No. 1",
			"Raisoni Farm", "Raj Bhavan", "Raja Bahadur", "Raja Bungalow",
			"Rajaram Pul", "Rajas Society", "Rajasthan Hotel",
			"Rajat Apartment", "Rajendra Pipe Company",
			"Rajendra Nagar / Nal Stop", "Rajendra Nagar",
			"Rajguru Nagar / Khed", "Rajguru Nagar Vidhyalaya",
			"Rajiv Gandhi Nagar", "Rajlaxmi Residency", "Rajmata Complex",
			"Rajmudra Society", "Rajwade Bungalow", "Rakshak Nagar",
			"Rakshak Society", "Rakshalekha Society", "Ram Society",
			"Raman Baug School", "Ram Baug", "Ramkrishna Mangal Karyalaya",
			"Ramkrishna Paramhans", "Ramkrishna Rasayan Kharkhana",
			"Ram Nagar Bharat Electronic Co.", "Ram Nagar", "Ramoshi Gate",
			"Ramoshi Wadi", "Ramtekadi", "Ram Wadi Jakat Naka", "Ram Wadi",
			"Ramyanagri", "Rangankhair", "Range Hills Circle 1",
			"Range Hills Circle 2", "Range Hills Corner", "Rangicha Odha",
			"Ranvara", "Ranwal Bungalow", "Ras Shala",
			"Rasta Peth Power House", "Raste Wada", "Raut Wadi", "Ravet Pul",
			"Ravet", "Raviraj Residency", "RD Colony", "Refund Company",
			"Renuka Bungalow", "Rhata Wade Boudh Wasti", "Rohakal Phata",
			"Rokdoba Mandir", "RTO", "Ruby Hall", "Runwal Hospital",
			"Rupee Nagar", "Ruston Company", "S.K.F Colony", "S.K.F Corner",
			"S.N.D.T", "S.P. College", "S.T. Colony", "S.T. Depot",
			"S.T. Regional Office", "S.T. Stand", "S.T. Workshop",
			"Sable Waghire College", "Sachapir Street", "Sadalbaba Darga",
			"Sadalbaba", "Sadanand Nagar", "Sadashiv Haud",
			"Sadashiv Peth Haud / Kunte Chowk", "Sadesatranali",
			"Sadguru Nagar / Desai Clinic", "Sadguru Nagar",
			"Sadhna Vidhyalaya", "Sadhunana Wasti", "Sadhu Vaswani Chowk",
			"Sagar Hotel", "Sahajanand Society", "Sahakar Panch Ratna",
			"Sahakari Sanstha", "Sahakar Nagar", "Sahastrabuddhe Samadhi",
			"Sahavas Society", "Sahitya Parishad", "Sai Chowk (Delux)",
			"Sai Cjpwl", "Sai Complex", "Sai Corner", "Sai Dham",
			"Sai Industries", "Sai Palace", "Saikripa", "Saimandir",
			"Sainath Nagar", "Sainik Wadi", "Sakal Office", "Sakal Nagar",
			"Saket Society", "Sakore Mala", "Salunke Hospital",
			"Salunke Vihar", "Samadhi Mandir", "Samartha Vidhyalaya",
			"Samarth Nagar", "Sambhaji Baug", "Sambhaji Chowk",
			"Sambhaji Pool", "Sambhaji Pul Corner", "Sambhaji Nagar",
			"Sambhaji Park/ Suvarn Park", "San Phala Company", "Sanas Baug",
			"Sanas Wadi", "Sancheti Hospital", "Sandesh Model Company",
			"Sandwik Company", "Sane Chowk", "Sane Wadi", "Sanfasta Company",
			"Sangam Metal Company", "Sangam Wadi", "Sangam Wadi Shala",
			"Sanghavi", "Sanghavi Chowk", "Sanghavi College", "Sanghavi Phata",
			"Sanghavi Sandas", "Sanghavi Gaon",
			"Sanghavi Gaon/ Vasant Dada Putala", "Sangrun", "Sangrun Phata",
			"Sanghavi Market", "Sanjay Park", "Sankesh Model Colony",
			"Sanket Vihar", "Sanmbhaji Park", "Sant Company",
			"Sant Dharmaji Samadhi", "Sant Gadge Maharaj Pul",
			"Sant Janabai Vastigrah", "Sant Kabir Chowk",
			"Sant Namdev Vidhyalaya", "Santosh Nagar", "Sanvi Company",
			"Sapika", "Sapras Post", "Sarang Society", "Sarasbaug",
			"Sarbatwala Chowk", "Sarbatwala Chowk/ batliwala chowk",
			"Sarpodyan", "Servants Corner", "Sasane Nagar", "Sase Wadi",
			"Sasoon", "Sasoon Hospital / Collector Office", "Sasoon Hospital",
			"Saste Phata", "Saswad", "Satav High School",
			"Satav Wadi / Gondhale Nagar", "Satav Wadi", "Sathe Biscuits",
			"Savant College", "Savant Vihar", "Savarkar Bhavan",
			"Savata Mandir", "Savata Mali Madir", "Sayali Restaurant",
			"Sayyad Nagar", "Servants Quarter", "Sevasadan", "Shagun Chowk",
			"Shahu Chowk", "Shahu Nagar", "Shanipar", "Shanipar / Mandai",
			"Shaniwar Wada Corner", "Shaniwar Wada", "Shankar Maharaj Math",
			"Shankar Wadi", "Shanti Nagar", "Sharada Arcade",
			"Shashkiy Vishram Grah Poud", "Shashtri Nager Colony",
			"Shashtri Nagar Corner", "Shashtri Nagar", "Shashtri Chowk",
			"Shashtri Park", "Shau Chowk", "Shedge Wasti", "Shel Pimpal Gaon",
			"Shelar Wasti", "Shelar Wadi", "Shel Gaon", "Shelke Wasti",
			"Sher-e-Punjab", "Sheti Mahamandal", "Shikapur Phata",
			"Shimala Office", "Shinde Chatri", "Shinde Farm", "Shinde Nagar",
			"Shinde Petrol Pump", "Shinde Wasti", "Shinde Wadi",
			"Shipra Society", "Shirish Bungalow", "Shirke Co.",
			"Shirke Company", "Shirole Petrol Pump", "Shiroli Phata",
			"Shitala Nagar", "Shitole Mala", "Shitole Nagar", "Shitole Wasti",
			"Shiv Pushpak Park Chowk", "Shivaji Housing Society",
			"Shivaji Maratha", "Shivaji Market", "Shivaji Park",
			"Shivaji Putala", "Shivaji Stadium", "Shivaji Maratha High School",
			"Shivaji Nagar Station",
			"Shivaji Putala / Ashirwad Mangal Karyalaya",
			"Shivale Wasti Shala", "Shivam Industries",
			"Shivanand Enclave Company", "Shivane Gaon", "Shivapur Baug",
			"Shivapur Wada", "Shivar Hotel", "Shivarkar Baug",
			"Shivarkar Udyan", "Shivdarshan", "Shivneri Poultry Farm",
			"Shivpushpak Park", "Shivratna Mangal Karyalaya",
			"Shivre Gaon Phata", "Shivshankar Chowk",
			"Shivshankar Mangal Karyalaya", "Shivshankar Super Market",
			"Shivtharwadi Phata", "Shivtharwadi", "Shivtrith Nagar Corner",
			"Shivtrith Nagar", "Shjivaji Nagar station", "Shri Nagar",
			"Shubham Hotel", "Shubham Society", "Simla Office", "Sind Colony",
			"Sindhu Nagar", "Sing Colony", "Sinhgad Hotel",
			"Sinhgad Paitha/ Aatkarwadi", "S.K.F. Company", "Smashanbhumi",
			"Smate Society", "SMZ Company", "SN Karyalaya", "SNDT College",
			"Somaji Khat Karkhana", "Soma Nagar", "Somatane Phata",
			"Someshwar Phata", "Somji Khat Karkhana", "Somnath Nagar",
			"Sonai Karyalaya", "Sonai Mangal Karyalaya", "Sonawane Hospital",
			"Sonya Maruti Chowk", "Sopan Baug", "Sortap Wadi",
			"Spartal Company", "Spicer College Press",
			"Splendor Country Club Gate No.2", "Sriman Society",
			"Sriram Company", "SRP Camp / Post office", "SRP Main Gate",
			"SRP Quarter", "St. Mira College", "Stadium", "Star Garden",
			"State Bank Colony", "Steel Tube Company", "Subhanshah Darga",
			"Subhash Vidhyalaya", "Sudarshan Nagar", "Sukhsagar Nagar",
			"Sun city", "Sundarabai Shala", "Sundarban", "Sundar Nagar",
			"Supply Depot", "Surbhi", "Surya Hospital",
			"Suryakiran Khat Kharkhana", "Sus Khind", "Susgaon", "Susphata",
			"Sutar Davakhana", "Sutar Hospital", "Sutardara", "Sutar Wadi",
			"Suvarnarekha Bungalow", "Swami Samartha School",
			"Swami Vivekanand Chowk", "Swargate", "Swargate Corner",
			"Swargate Janki Hall", "Swargate Police Line", "Sweet Mart",
			"Swimming Pul", "Symbiosis College", "T.B. Hospital", "Tadigutta",
			"Tadiwala Road", "Tajane Wasti", "Talab Farm", "Talawade",
			"Tale Gaon Khind", "Tale Gaon Nagarparishad", "Tale Gaon Phata",
			"Tale Gaon Station", "Tale Gaon",
			"Tale Gaon Dabhade / Vadgaon Maval Phata", "Tale Gaon Dhamdhere",
			"Tale Gaon S.T. Stand", "Talemale", "Tangde Bhandhu Mala",
			"Tanna Protex", "Tapkie Bungalow", "Tapkir Wasti", "Tapkir Nagar",
			"Tapovan Mandir", "Tapovan", "Tata Guardroom", "Tathawade",
			"Tathawade Phata", "Taware Colony", "TB 2", "Telco Colony",
			"Telco Company", "Telco Hostel", "Telephone Bhavan",
			"Telyachi Wasti", "Tendulkar Wasti", "Thakur Wasti",
			"Thamane Wasti", "Ther Gaon Corner", "Ther Gaon Phata",
			"Thermax Chowk", "Thermax Company", "Theur Factory",
			"Theur Gaon Phata", "Thite Wasti", "Tikone Godown", "Tilak Baug",
			"Tilekar Wasti", "Timber Market", "Tingre Nagar",
			"Training School /chitrashala", "Transport Nagar",
			"Transport Nagari", "Trimurti Bungalow / City Bank",
			"Trimurti Bungalow", "Trimurti Dhaba", "Trimurti Garden",
			"Trimurti Hall", "Trimurti Housing Society",
			"Trimurti Mangal Karyalya", "Trimurti Nagar",
			"Trumurti Gaurden / Aroh Mangal Karyalaya",
			"Tukai Tekadi / Bhekarai Nagar", "Tukai Nagar", "Tukaram Nagar",
			"Tukaram Park", "Tulapur Phata", "Tulsi Chemical", "Tulsi Company",
			"Tupemala", "U.P. Hotel", "UCO Bank", "Uday Baug",
			"Undri Gaon Shala", "Undri Gaon", "United Western Bank",
			"United Western Society", "Upper Indira Nagar Corner",
			"Upper Indira Nagar", "Urali Kanchan", "Urawade Gaon",
			"Urali Devachi", "Urali Devachi Phata", "Uttam Nagar",
			"Uttchav Mangal Karyalaya", "Vadacha Stop", "Vada Gaon Bu.",
			"Vada Gaon Maval Phata", "Vada Gaon Phata", "Vada Gaon Buna",
			"Vada Gaon High way Pool Corner", "Vada Gaon Shala",
			"Vada Gaon Sheri", "Vada Gaon Shinde", "Vaidu Wasti", "Vaidu Wadi",
			"Vaishnodevi", "Vak Wasti", "Vaki Khurd", "Vallabh Nagar",
			"Vanaz Company", "Vanaz Corner", "Vanvadi School", "Vardade Phata",
			"Vardade", "Varve Gaon", "Vasant Baug", "Vasant Dada Putala",
			"Vasant Talkies", "Vasundhar Lawns", "Vatare Mala", "Veet Bhatti",
			"Veet Karkhana", "Velu Gaon Phata", "Venkateshwara Poultry Farm",
			"Ventri Biology Company", "Venutai Chavhan College",
			"Venutai College", "Vhisab Depot", "Vidi Kanmgar Vasahat",
			"Vidhya Nagar", "Vidhya Nagar/ Swapna Ganga Bungalow",
			"Vidhyapeth Mess", "Vidhyashwar Marble", "Vijay Maruti Mandir",
			"Vijay Nagar", "Vijay Oil Mill", "Vijay Talkies",
			"Vikas Nagar Corner", "Vikas Nagar", "Vikrikar Bhavan",
			"Viman Nagar Gate", "Viman Nagar", "Viman Nagar Corner",
			"Vipro Company Circle no. 1 Emcure Co.",
			"Vipro Company Circle no. 2 Emcure Co.", "Vishal Nagar",
			"Vishnu Udyog", "Vishram Grah", "Vishrambaug Wada", "Vishramdham",
			"Vishrantwadi", "Vishveshwar Bank", "Vishveshwar",
			"VIT College Hostel", "VIT Hostel", "Veetbhatti",
			"Vitthal Mandir lMangal Karyalaya", "Vitthal Mandir",
			"Vitthal Wadi Phata", "Vitthalbaba Darga",
			"Vitthal Wadi Jakat Naka", "Vitthal Wadi Mandir",
			"Vivekanand Society", "Vrindavan Society", "Vrudhashram",
			"Wadache Zaad", "Wadachi Wadi", "Wadar Wadi", "Waddara Bandhara",
			"Wade Bolai", "Wadia Bungalow", "Wadia College", "Wadilal",
			"Wadkar Mala", "Wadki Gaon", "Wadki Phata",
			"Wadki Phata / 10 Mail", "Wadkinala", "Wadmukh Wadi", "Waghdoha",
			"Waghjai Mandir", "Wagholi", "Waid Wadi", "Waidu Wasti",
			"Waje Wadi Choufula", "Waje Wadi Phata", "Wakad Chowk",
			"Wakad Corner", "Wakad Highway", "Wakad Phata",
			"Wakad Police Station", "Wakad", "Wakde Wadi", "Wakhar Mahamandal",
			"Waki Budruk", "Waki Khurd", "Walhekar Wadi Corner",
			"Walhekar Wadi Phata", "Walhekar Wadi", "Walke Mala",
			"Walke Wasti", "Wallabh Nagar", "Wanawadi Bazaar",
			"Wanawadi Corner", "Warje Gaon", "Warje Jakatnaka",
			"Warje Malwadi", "Warje Shala", "Warje", "Warje Naka",
			"Washer Mahamandal", "Wastu Udyog", "Water Supply", "Water Tank",
			"Waterworks", "Wathare Mala", "Wekfield Company", "West End",
			"Westend Talkies", "Widi Kamgar Vasahat", "Wireless Colony",
			"Wireless", "WNC Company", "Wonder City", "Y.C.M", "Yadav vasti",
			"Yamina Post Office", "Yamuna Nagar", "Yamuna Nagar Corner",
			"Yamuna Nagar Police Station", "Yashoda Garden", "Yashoda Nivas",
			"Yashwant Nagar", "Yerawada", "Yewalewadi / Zilla Parishad School",
			"Yewlewadi Z.P. Shala", "Z.F. Company", "Zala Complex",
			"Zambe Phata", "Zambe Phata/ Punawale", "Zendemala",
			"Zende Wadi Phata", "Zenith Company", "Zero Boys Bakery",
			"Zero Boys", "Zilla Parishad Shala", "Zilla Parishad" };
	String srcu,destu;
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		//requestWindowFeature(Window.FEATURE_NO_TITLE);
		//getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
		setContentView(R.layout.route);
		
		Button bFMR = (Button) findViewById(R.id.bFMR);
		final AutoCompleteTextView ac2 = (AutoCompleteTextView) findViewById(R.id.acDest);
		final AutoCompleteTextView ac1 = (AutoCompleteTextView) findViewById(R.id.acSrc);
		ArrayAdapter<String> adapter = new ArrayAdapter<String>(Routes.this,
				android.R.layout.simple_dropdown_item_1line, paths);
		ac2.setAdapter(adapter);
		ArrayAdapter<String> adapter2 = new ArrayAdapter<String>(Routes.this,
				android.R.layout.simple_dropdown_item_1line, paths);
		
		//adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
		
		ac1.setAdapter(adapter);
		ac2.setAdapter(adapter2);
		ac1.setOnItemSelectedListener(this);
		ac2.setOnItemSelectedListener(this);
		
		bFMR.setOnClickListener(new View.OnClickListener() {
			
			@Override
			public void onClick(View v) {
				// TODO Auto-generated method stub
				srcu = ac1.getText().toString();
				destu = ac2.getText().toString();
				setContentView(R.layout.displayres);
//				Intent nayawala = new Intent("com.example.stoppointui.Display");
//				startActivity(nayawala);
				initialize();
				sd.setText(srcu);
				dd.setText(destu);
			}

			
		});
	}
	public void initialize() {
		// TODO Auto-generated method stub
		sd = (TextView)findViewById(R.id.tvSrcd);
		dd = (TextView)findViewById(R.id.tvDestd);
	}
	public void onItemSelected(AdapterView<?> parent, View v, int position,
			long id) {

//		switch (position) {
//		case 0:
//			// Whatever you want to happen when the first item gets selected
//			break;
//		case 1:
//			// Whatever you want to happen when the second item gets selected
//			break;
//		case 2:
//			// Whatever you want to happen when the third item gets selected
//			break;
//		}
	

	}

	@Override
	public void onNothingSelected(AdapterView<?> parent) {
		// TODO Auto-generated method stub

	}
	
}
